### ISSUE TITLE
Part of the deprecated rule "no-unsupported-features" apparently is not supported by the new counterparts

### ISSUE THREAD

**Issue by papb** [mysticatea/eslint-plugin-node#144]
I know that `no-unsupported-features` has been deprecated ([here](https://www.npmjs.com/package/eslint-plugin-node#deprecated-rules)). But since it was a "recommended" rule and the two new rules are also "recommended", the default behaviour should be the same, right?

```javascript
// file.js
const x = 1;
```

```javascript
// .eslintrc.json
{
    "env": {
        "es6": true,
        "node": true
    },
    "plugins": ["node"],
    "extends": ["eslint:recommended", "plugin:node/recommended"]
    "rules": {}
}
```

```
$ node --version
v6.11.1
$ npm init -y
$ node -p require('./package.json').engines
undefined
$ npm install --save eslint eslint-plugin-node
```

Now, running `./node_modules/.bin/eslint .` gives only one error (`no-unused-vars`). If I go back to `.eslintrc.json` and add the rule `"node/no-unsupported-features": "error"`, running it again yields two errors (`node/no-unsupported-features` and `no-unused-vars`).

Why would adding a deprecated rule makes any difference on the behavior of eslint if the new rules are a replacement for the old one? This seems wrong.

**Comment by mysticatea** [comment]
Thank you for this issue.

No. Those are not the same because the `no-unsupported-features` rule is old. For example:

- The default Node.js version is `6.0.0` on `no-unsupported-features/*` rules because `4.0.0` is EOL. On the other hand, it's `4.0.0` on `no-unsupported-features` rule because `4.0.0` was not EOL at that time.
- The `no-unsupported-features` doesn't know newer features Node.js 11 supported.
