### ISSUE TITLE
Possible breaking change: Exports no longer be recognized as an assignable global in 9.0

### ISSUE THREAD

**Issue by Twipped** [mysticatea/eslint-plugin-node#175]
Today I bumped my project up to using 9.1 from 8.0.1, and immediately started getting linting errors on my exports declarations. I have my project set to use `'node/exports-style': [ 'error', 'exports', { 'allowBatchAssign': true } ],` so that it enforces `module.exports = exports = ` for exports assignment.

After updating the plugin, eslint doesn't seem to recognize `exports` as an assignable global. I get flags on both `no-global-assign` and `no-implicit-globals` for the `exports` assignment. Reverting back to 8.0.1 removed the flags.

I think this happened with the restructuring of `node/recommended`, because the new structure explicitly sets `globals.exports` to `'off'` and then to 'readonly', overriding the value that comes from the eslint `node` environment. I managed to correct it by explicitly turning it back on in my eslintrc file.

**Comment by mysticatea** [comment]
Hi. Thank you for your report.

- Because this package follows semantic versioning, a major version contains breaking changes intentionally.
- [Node.js doesn't define `require`, `exports`, `module.exports`, `__filename`, and `__dirname` in module mode](https://nodejs.org/api/esm.html#esm_no_code_require_code_code_exports_code_code_module_exports_code_code_filename_code_code_dirname_code). Therefore `node/recommended` makes those off if [`package.json` has `type: "module"`](https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field).

**Comment by Twipped** [comment]
Ok, I think my point here was missed.

1. This was an undocumented breaking change, which took me the better part of three hours to solve because at first I couldn't tell where it was coming from. Extends just suddenly stopped working in my linting config, and the errors I was getting didn't make any sense for where the actual problem ended up being.
2. This change means that `allowBatchAssign: true` cannot be used because another part of the plugin is blocking it.
3. My package.json does not have `"type": "module"`, this is a standard CommonJS library that I'm in the process of updating from Node 4.

At a minimum it should be documented that `globals.extends` needs to be set back to on to be able to use allowBatchAssign on top of  `node/recommended` settings.

**Comment by mysticatea** [comment]
Ah, I'm sorry for my misunderstanding.

So this issue is the error of `no-global-assign` rule that is caused by [lib/configs/recommended-script.js#L10](https://github.com/mysticatea/eslint-plugin-node/blob/b757c3ec06aa95af351ad19ea7d0357c5ed2eda7/lib/configs/recommended-script.js#L10) (`exports: "readonly",`) rather than `node/exports-style`'s errors?

I thought that the assignment to `exports` doesn't make sense because it doesn't affect, but indeed, `module.exports = exports =` works fine.

We should make a new rule to warns `exports =` but allows `module.exports = exports =`, rather than leaving it to `no-global-assign` rule.

**Comment by Twipped** [comment]
Awesome! Thank you!
