### ISSUE TITLE
[no-deprecated-api] Incorrect target version matching

### ISSUE THREAD

**Issue by julien-f** [mysticatea/eslint-plugin-node#176]
I've seen this issue in a project that as `engines.node` set to `>=6.9`, but this plugin reports that `url.resolve` is deprecated and that I should use `url.URL` instead, but it is only supported starting from Node 6.13.

I think the problematic code is: https://github.com/mysticatea/eslint-plugin-node/blob/b757c3ec06aa95af351ad19ea7d0357c5ed2eda7/lib/rules/no-deprecated-api.js#L667

But checking the intersection is not good enough, ideally we must make sure that the target range (`version`) is included in the supported range (`supported`).

Unfortunately it does not appear to be supported at this time by `semver`, but we could simply check that the minimum version of the target range is greater than or equal to the supported version:

```js
gte(minVersion(version), supported)
```

**Comment by renarsvilnis** [comment]
Hi,
I'm migrating an existing node v8 code base to typescript noticed that when added I `eslint-plugin-node` that I get `no-deprecated-api`:

`error  'url.parse' was deprecated since v11.0.0. Use 'url.URL' constructor instead`

In `package.json` I have set to support **ONLY** node 8 version:

`{"engines: {"node": "^8.x.x"}}` // a.k.a '>=8.0.0 <9.0.0'

For me, it doesn't seem logical that error is thrown as API is not yet depreciated in the node.js range my app supports. Feels more like `warning` than `error`, as I the "new" API is available.

**Is that behaviour intentional?**

Initially was going insane thinking, that the eslint plugins I extend are overriding the stuff, so I verified that `no-deprecated-api` receives the correct supported range specified in `package.json`.

```
Range {
  options: { loose: false, includePrerelease: false },
  loose: false,
  includePrerelease: false,
  raw: '^8.x.x',
  set: [ [ [Comparator], [Comparator] ] ],
  range: '>=8.0.0 <9.0.0'
}
```

**Comment by mysticatea** [comment]
Hi @renarsvilnis. your question is not related to this issue. The `'url.URL' constructor` has been supported since Node 6.13.0 correctly.

> Is that behaviour intentional?

Yes. The `no-deprecated-api` reports all deprecated APIs the rule can check, regardless of when deprecated. If you don't care the deprecated APIs, you can disable the rule. Because all deprecated APIs are never removed without major version up regardless of when deprecated.

**Comment by julien-f** [comment]
Hi,

As I said [there](https://github.com/mysticatea/eslint-plugin-node/pull/164#issuecomment-533121446), it still not completely fixed.
