### ISSUE TITLE
node/no-unpublished-import errors on an import that meets rule criteria.

### ISSUE THREAD

**Issue by stormmuller** [mysticatea/eslint-plugin-node#187]
Recently this package was updated to v10.0.0 and `node/no-unpublished-import` was added to `_commons.js`.

This caused one of our imports to error out. We import `"sequelize-mock": "^0.10.2"` as a devDependency. When trying to import the module in one of our own files the error is thrown. `import SequelizeMock from 'sequelize-mock';` 

The rule states:
```
"files" field of package.json includes the file or "files" field of package.json does not exist.
.npmignore does not include the file.
```
Looking at the [sequelize-mock repo](https://github.com/BlinkUX/sequelize-mock) there is no files field in the package.json and there is no `.npmignore` file. So this should be considered published?

**Comment by mysticatea** [comment]
That criteria are for the importer.

If the importee was declared as a `devDependencies`, production files should not import it. The rule considers the files which are included in `files` field and/or not included in `.npmignore` as production files.

**Comment by stormmuller** [comment]
So just for clarity the rule won't apply to to any packages I specify in the `devDependencies`?

**Comment by mysticatea** [comment]
The goal of the rule is to prevent `MODULE_NOT_FOUND` errors after `npm publish`.

The rule works on your production files. The following files are considered as production files:

- `files` field contains.
- `.npmignore` file doesn't contain.

The production files can import the following items:

- Other production files.
- Packages in `dependencies` or `peerDependencies`.

If a production file imported other files such as `devDependencies`, it will be warned because `devDependencies` will be lost after `npm publish`.
