### ISSUE TITLE
Cannot find module 'eslint-plugin-node'

### ISSUE THREAD

**Issue by wzkun** [mysticatea/eslint-plugin-node#196]
Failed to load plugin 'node' declared in '.eslintrc': Cannot find module 'eslint-plugin-node'.
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-node' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-node' isn't installed correctly.

**Comment by mysticatea** [comment]
Thank you for your report.

But I'm confused. What do you want to solve?

**Comment by wzkun** [comment]
![image](https://user-images.githubusercontent.com/39115378/68659244-e0d94480-0571-11ea-95e9-def62db73607.png)
I upgrade the devDependencies in picture, then in vscode ,it outputs this error.

**Comment by mysticatea** [comment]
ESLint 6.0.0 has changed the loading logic of plugins drastically. Please see [the migration guide](https://eslint.org/docs/user-guide/migrating-to-6.0.0#package-loading-simplification).

**Comment by wzkun** [comment]
Actually, I installed eslint and eslint-plugin-xx through yarn locally,but it still output error.
![image](https://user-images.githubusercontent.com/39115378/68668046-4d5c3f80-0582-11ea-9068-38f8365d1781.png)

**Comment by mysticatea** [comment]
To make sure:

1. Check if CLI command (`npx eslint path/to/a/file`) works or not.
1. Check if all your plugins are installed in `/Users/wzkun/workspace/javascript/node_modules`.
1. Check if your vscode has been restarted after you upgrade packages.

Well, because this is the repository of a plugin, this is not the best place to ask help about the behavior of ESLint itself. Please ask in [the chat room](https://gitter.im/eslint/eslint) or other developer forums.

**Comment by wzkun** [comment]
![image](https://user-images.githubusercontent.com/39115378/68723954-25f28a80-05f5-11ea-86f7-03fcbc5ef983.png)
 1. All my plugins are installed in /Users/wzkun/workspace/javascript/node_modules.
2. My vscode has been restarted after you upgrade packages.

**Comment by paulincai** [comment]
@wzkun  totally annoying I may say ... Just came out of nowhere ...
