### ISSUE TITLE
[v11] Cannot find module 'eslint-plugin-node'

### ISSUE THREAD

**Issue by numToStr** [mysticatea/eslint-plugin-node#203]
Previously It was working fine. I don't know when It stopped working. I already followed this issue #196 but couldn't find a solution.

I am getting the following error in VS Code. All other plugins are working fine
```
(node:24822) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'node' declared in 'packages/server/.eslintrc.json': Cannot find module 'eslint-plugin-node'
```
**If I disable the `eslint-plugin-node` in `.eslintrc` everything works fine.**

BTW I am using yarn workspaces.

### Folder Structure
```
> node_modules
> packages
    > client
    > server
    > core
```

### .eslintrc.json
```json
{
    "env": {
        "es6": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "airbnb-base",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "prettier",
        "prettier/@typescript-eslint",
        "plugin:node/recommended",
        "plugin:import/errors",
        "plugin:import/warnings",
        "plugin:import/typescript"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 2020,
        "sourceType": "module",
        "project": "packages/server/tsconfig.json"
    },
    "plugins": ["@typescript-eslint"],
    "rules": {
        "max-classes-per-file": ["error", 10],
        "newline-before-return": "error",
        "class-methods-use-this": "off",
        "no-underscore-dangle": ["error", { "allow": ["_id"] }],
        "no-useless-constructor": "off",
        "@typescript-eslint/no-empty-function": [
            "error",
            { "allow": ["constructors"] }
        ],
        "import/no-cycle": "off",
        "import/prefer-default-export": "off",
        "@typescript-eslint/no-useless-constructor": "off",
        "@typescript-eslint/explicit-function-return-type": [
            "off",
            { "allowExpression": true }
        ]
}

```

### Environment
node: 12.14.0
eslint: 6.8.0
eslint-plugin-node: 11.0.0
typescript: 3.7.4

**Comment by mysticatea** [comment]
Happy New Year!

"Cannot find module" error is not a problem of this repository. That error happens in the consumers of this plugin.

1. Make sure to restart VSCode after install/update packages.
  If it works fine after restart, it was a problem of the internal state of VSCode.
1. Check if `node_modules/eslint-plugin-node` exists or not.
  If not exist, please install it correctly.
1. Run `node -p "require.resolve('eslint-plugin-node')"` on the root directory of your project.
  If it doesn't print the path of `eslint-plugin-node`, it's a problem of `yarn`. Please report to `yarn` repo.
1. Check if the CLI command works or not: `npx eslint packages/server`
  If the CLI command worked fine, this is a problem of `vscode-eslint`. Please report to `vscode-eslint` repo.
1. If the CLI command didn't work, it's possibly a problem of `eslint`.

Because this is the repository of a plugin, this is not the best place to ask help about the behavior of ESLint itself. Please ask in [the chat room](https://gitter.im/eslint/eslint) or other developer forums.
