### ISSUE TITLE
"plugin:node/recommended" generates: Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by thernstig** [mysticatea/eslint-plugin-node#230]
There was another issue like this, seen here: https://github.com/mysticatea/eslint-plugin-node/issues/135 but it was closed. But  I felt it was warranted to open a new issue since this seems to be a problem with this plugin, which goes against the answer in that issue.

I have the following configuration:

```json
  "extends": [
    "airbnb-base",
    "plugin:node/recommended",
    "plugin:jest/recommended",
    "plugin:jest/style",
    "plugin:jsdoc/recommended",
    "plugin:prettier/recommended"
  ],
```

If I remove `"plugin:node/recommended",`, the error ` Parsing error: 'import' and 'export' may appear only with 'sourceType: module'` goes away. So it is this plugin generating this error somehow.

The reason why I get this is because I use commonjs (i.e. `require()`) instead of ecmascript modules (i.e. `import`) in my code. But for Jest test cases, I use `import` because those are transformed by babel anyway. So I get the error in those files only.

I can work around this by setting an overrides to use another `sourceType` like so:

```json
  "overrides": [{
    "files": ["path/to/some/file.js", "path/to/some/folder/**.js"],
    "parserOptions": {
      "sourceType": "module"
    }
  }]
```

But the question is, why is this error generated at all due to the inclusion of `"plugin:node/recommended",`?

**Comment by thernstig** [comment]
Another funny thing I noticed now. If I keep `"plugin:node/recommended",` and add the overrides as explained above, the error changes to `Import and export declarations are not supported yet. eslint (node/no-unsupported-features/es-syntax`.

I can ignore that as well in the `"overrides"` section, but it might be related.

**Comment by mysticatea** [comment]
The `plugin:node/recommended` config has `parserOptions.sourceType` value. If `$CWD/package.json` has [`type:"module"`](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_package_json_type_field), it's `"module"`. Otherwise, it's `"script"`. Because Node.js switch the type of `*.js` files by `package.json`.

If you want to use recommended config for ES modules, use `plugin:node/recommended-module`. See also https://github.com/mysticatea/eslint-plugin-node#-configs

**Comment by thernstig** [comment]
@mysticatea I do not think I was clear enough. Without the usage of this package (`eslint-plugin-node`) I have no error message at all in the Jest test cases that uses `import`. When I install this plugin via npm, and add `"plugin:node/recommended",` I get the error `arsing error: 'import' and 'export' may appear only with 'sourceType: module'`. 

What I was refering to was the fact that in https://github.com/mysticatea/eslint-plugin-node/issues/135 it was said:

>This is not the output of this plugin.

But I cannot see how that is true, as I do not have that error without this plugin. Would it not be good if the error message somehow indicats it comes from this plugin?

**Comment by mysticatea** [comment]
> Without the usage of this package (eslint-plugin-node) I have no error message at all in the Jest test cases that uses import.

Because you extend `airbnb-base` and it has `parserOptions.sourceType` with `"module"`.
`plugin:node/recommended` overrides it with Node.js's spec I described in https://github.com/mysticatea/eslint-plugin-node/issues/230#issuecomment-640483398. The matter is the value of `parserOptions.sourceType` setting in your config.

**Comment by thernstig** [comment]
I see! Thanks for that. Wouldn't the proper way be to solve it like I did then instead, to just override the parserOptions for the jest paths? (and to leave it and still use `"plugin:node/recommended"`?

**Comment by mysticatea** [comment]
Your workaround (overrides `parserOptions.sourceType`) is right.

But it may be nice to use `plugin:node/recommended-module` instead.

```
  "overrides": [{
    "files": ["path/to/some/file.js", "path/to/some/folder/**.js"],
    "extends": "plugin:node/recommended-module"
  }]
```

- It configures the rules of this plugin for ES modules. For example, it reports some global variables that we cannot use in ES modules, and tweaks the `node/no-unsupported-features/es-syntax` rule to ignore ES modules syntax.

Or, if you are sure that all `*.js` files are ES modules, you can use `plugin:node/recommended-module` instead of `plugin:node/recommended`:

```
  "extends": [
    "airbnb-base",
    "plugin:node/recommended-module",
    "plugin:jest/recommended",
    "plugin:jest/style",
    "plugin:jsdoc/recommended",
    "plugin:prettier/recommended"
  ],
```

**Comment by thernstig** [comment]
Closing this, as you have so thoroughly explained it all. Hopefully this helps someone else as well.

**Comment by ljharb** [comment]
@mysticatea `.mjs` files are always ESM, and `.cjs` files are always CJS, regardless of the `type` setting. I'm getting a linting error on `.mjs` files even when using `overrides` to set `version` to a node version that supports ESM natively (`^12.17 || ^13.7 || >= 14`).

Should this be reopened, or should it be a separate issue?

**Comment by mysticatea** [comment]
> [lib/configs/recommended.js#L13-L16](https://github.com/mysticatea/eslint-plugin-node/blob/cd97880ca2792db47c7952ac517e9e32d2ec783e/lib/configs/recommended.js#L13-L16)

The `recommended` config has `overrides` setting for `*.mjs` and `*.cjs`.
Please make sure other shareable configs that are loaded after `plugin:node/recommended` or your config don't have `parserOptions.sourceType: "script"` setting.

Or... `node/no-unsupported-features/es-syntax` rule reports experimental features as unsupported, so you need to configure `ignores` option as well, similar to [lib/configs/recommended-module.js#L22-L25](https://github.com/mysticatea/eslint-plugin-node/blob/cd97880ca2792db47c7952ac517e9e32d2ec783e/lib/configs/recommended-module.js#L22-L25). ESM looks got stable at v15.3.0 (this has not been applied. I will update this plugin within this month).

**Comment by ljharb** [comment]
I’d suggest using “unflagged” and not “not experimental”, personally. It’s fully usable with no experimental warning in node v12.17.
