### ISSUE TITLE
"'util.isArray' was deprecated since v4. Use 'Array.isArray()' instead" is sometimes skipped

### ISSUE THREAD

**Issue by nfriedly** [mysticatea/eslint-plugin-node#65]
I haven't figured out exactly what causes this yet, but the rule `'util.isArray' was deprecated since v4. Use 'Array.isArray()' instead` sometimes doesn't get enforced. See, for example, https://travis-ci.org/watson-developer-cloud/node-sdk/builds/203611751 where the exact same code was linted on node.js v4, v6, and v7 - the rule correctly caught usages of `util.isArray()` and failed the build on v4, but it incorrectly missed those same usages when running on v6 and v7. 

I'm not sure that the test is dependent on the Node.js version though - in retrying locally, I managed to get it to both pass and fail my linting on node v4, so I think that the trigger is something else.

**Comment by mysticatea** [comment]
Thank you for the report.

However, after I investigated this, I have found this is not a problem of `eslint-plugin-node`.

`node/no-deprecated-api` rule is warning about Node.js core modules. If you have the module which has the same name as a core module then `node/no-deprecated-api` rule ignores it. Because [some deprecated core modules recommends a use of the thirdparty module which has the same name as itself](https://nodejs.org/api/punycode.html).

Now, your `watson-developer-cloud` module seems to depend on `util` module indirectly. And if `npm` make flatten dependencies, the thirdparty `util` module is chosen instead of core `util` module. The `npm` command bundled by Node.js 4 is npm v2, so it does not make flatten dependencies.

**Comment by mysticatea** [comment]
`browserify` seems to depend on thirdparty `util` module.
I'm considering if I change the behavior of `node/no-deprecated-api` about indirect dependencies.

**Comment by mysticatea** [comment]
Just linking to #66.

**Comment by nfriedly** [comment]
Aah, I didn't think of that. Thanks for the clear explanation.

**Comment by nfriedly** [comment]
Awesome, thanks!
